data_fetching:
  fred_series_map:
    SOFR: 'SOFR'
    DGS10: 'DGS10'
    DGS2: 'DGS2'
    RRP: 'RRPONTSYD'
    VIX_FRED: 'VIXCLS'
    Reserves: 'WRESBAL'
    DTB3: 'DTB3'
  fred_move_ticker: 'MOVEIX'
  yahoo_tickers_map:
    Volatility_Index: '^MOVE'
    VIX: '^VIX'
    TLT_Close: 'TLT'
  nyfed_data_urls: [] # 新增此鍵，即使為空，以避免 KeyError
